server:
  port: 8888

eureka:
  instance:
    hostname: registry
    prefer-ip-address: true
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
  client:
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@registry:8761/eureka/

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
         native:
          search-locations: classpath:properties/ 
  rabbitmq:
    host: 192.168.0.110
    port: 5672
    username: admin
    password: admin
security:
  user:
    name: user
    password: ${CONFIG_SERVER_PASSWORD:password}
