# 开发配置
spring:
  datasource:
    url: jdbc:mysql://192.168.0.110:3306/ai_prescription?characterEncoding=utf-8&useSSL=false
    username: root
    password: citybaby123
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/ai_prescription?characterEncoding=utf-8
#    username: root
#    password: 123456

  redis:
    host: 192.168.0.110
    port: 6379
    password: yixiang129
    #cluster:
      #nodes: 127.0.0.1:6380,127.0.0.1:6381