# 生产配置
spring:
  datasource:
    url: jdbc:mysql://192.168.0.110:3306/hospitalinfo?characterEncoding=utf-8
    username: root
    password: citybaby123
    
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/hospitalinfo?characterEncoding=utf-8
#    username: root
#    password: 123456